# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: caa9b4ac48033bc2ff979e46b5f96693b4a9d932fb5032c4a4362af0c954e86e968591cd447362573bd8777d04d13691e2a60fd65ffd15dede44fce9e831e046

test:
  secret_key_base: 5dfb935094436590a78e533822904f00232120b5a8dd3eae6fa075db453af5e2a6144f39725f9067b33c6cbc54356ab6532893806f034dd736eb8f969dda986d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
